//      *********    DO NOT MODIFY THIS FILE     *********
//      This file is regenerated by a design tool. Making
//      changes to this file can cause errors.
namespace Expression.Blend.SampleData.OurSampleData
{
	using System; 

// To significantly reduce the sample data footprint in your production application, you can set
// the DISABLE_SAMPLE_DATA conditional compilation constant and disable sample data at runtime.
#if DISABLE_SAMPLE_DATA
	internal class OurSampleData { }
#else

	public class OurSampleData : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		public OurSampleData()
		{
			try
			{
				System.Uri resourceUri = new System.Uri("/AdvancedBlend;component/SampleData/OurSampleData/OurSampleData.xaml", System.UriKind.Relative);
				if (System.Windows.Application.GetResourceStream(resourceUri) != null)
				{
					System.Windows.Application.LoadComponent(this, resourceUri);
				}
			}
			catch (System.Exception)
			{
			}
		}

		private Games _Games = new Games();

		public Games Games
		{
			get
			{
				return this._Games;
			}
		}
	}

	public class GamesItem : System.ComponentModel.INotifyPropertyChanged
	{
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;

		protected virtual void OnPropertyChanged(string propertyName)
		{
			if (this.PropertyChanged != null)
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}

		private string _Name = string.Empty;

		public string Name
		{
			get
			{
				return this._Name;
			}

			set
			{
				if (this._Name != value)
				{
					this._Name = value;
					this.OnPropertyChanged("Name");
				}
			}
		}

		private double _Price = 0;

		public double Price
		{
			get
			{
				return this._Price;
			}

			set
			{
				if (this._Price != value)
				{
					this._Price = value;
					this.OnPropertyChanged("Price");
				}
			}
		}

		private string _ReleaseDate = string.Empty;

		public string ReleaseDate
		{
			get
			{
				return this._ReleaseDate;
			}

			set
			{
				if (this._ReleaseDate != value)
				{
					this._ReleaseDate = value;
					this.OnPropertyChanged("ReleaseDate");
				}
			}
		}

		private System.Windows.Media.ImageSource _CoverImage = null;

		public System.Windows.Media.ImageSource CoverImage
		{
			get
			{
				return this._CoverImage;
			}

			set
			{
				if (this._CoverImage != value)
				{
					this._CoverImage = value;
					this.OnPropertyChanged("CoverImage");
				}
			}
		}
	}

	public class Games : System.Collections.ObjectModel.ObservableCollection<GamesItem>
	{ 
	}
#endif
}
